server:
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/Ejemplo_arqui}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/arquitectura
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
apiDatos:
  url: "https://api.artic.edu/api/v1/artworks"
logging:
  level:
    org.springframework.security: DEBUG